# Example configuration file that:
#  - Has a private registry
#  - Ignores lodash dependency
#  - Disables version-updates
#  - Defines a group by package name, for security updates for golang dependencies

version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: "Asia/Kolkata"
  labels:
    - "dependencies"
  open-pull-requests-limit: 50
  ignore:
    - dependency-name: "python-telegram-bot"
    # Ignoring all ptb updates
    - dependency-name: "sqlalchemy"
    # Ignoring all sqlalchemy updates
